#Makefile opencv archlinux and debian

CC = gcc
GCC = g++

all:
	$(GCC) -Wall -Wunused -O3 atividade.cpp -o result -I /usr/include/opencv -L /usr/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_videoio


